services:
  app:
    build: .
    environment:
      - POSTGRES_URL=postgresql+asyncpg://postgres:postgres@db:5432/smedia
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=smedia
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  database: