"""stages

Revision ID: fad9243e859b
Revises: e959e88268ed
Create Date: 2023-08-27 16:53:37.289661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fad9243e859b'
down_revision: Union[str, None] = 'e959e88268ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('WELCOME', 'WAITING_FOR_MATERIAL', 'IDLE', name='userstage').create(op.get_bind())
    op.add_column('user', sa.Column('current_stage', sa.Enum('WELCOME', 'WAITING_FOR_MATERIAL', 'IDLE', name='userstage'), nullable=False))
    op.create_unique_constraint(None, 'user', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'current_stage')
    sa.Enum('WELCOME', 'WAITING_FOR_MATERIAL', 'IDLE', name='userstage').drop(op.get_bind())
    # ### end Alembic commands ###
